spring:
  application:
    name: DevReilway
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
<<<<<<< Updated upstream
      ddl-auto: update
=======
      ddl-auto: create-drop
>>>>>>> Stashed changes
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
